function run_main_fes()

%% CLEAR WORKSPACE
clc, close all

%% INPUT FILE
% input_file_elastic_test_13
% input_file_elastic_test_neoh
% input_file_elastic_neoh_footing
% input_file_thermo_elastic_test
% input_file_moving_heat_source
% input_file_thermo_elastic_htsrc_debug
% input_file_elastic_test_neoh_10x10
input_file_thermo_elastic_10x10_moving_heat_src

%% OPEN FILES FOR POST PROSESSING
output_folder       = 'output';

% Set tolerance
tol = 1.000E-8;

%% FLAGS
debug                      = 0;
enable_numerical_tangent   = 0;
write_tec                  = 0;
plot_load                  = 0;
plot_initial_configuration = 0;
plot_each_load_step        = 0;
plot_final_configuration   = 1;
save_solution_vectors      = 0;

sys_vars = struct('output_folder',output_folder,...
                  'mesh_input',mesh_input,...
                  'define_BC',define_BC,...
                  'int_rule',int_rule,...
                  'n_dim',n_dim,...    
                  'element_type',element_type,...
                  'physics',physics,...
                  'mat_para',mat_para,...
                  'node_p_el',node_p_el,...
                  'total_element_no',0,...
                  'total_node_no',0,...
                  't_para',t_para,...
                  'tol',tol,...
                  'debug',debug,...
                  'enable_numerical_tangent',enable_numerical_tangent,...
                  'write_tec',write_tec,...
                  'plot_load',plot_load,...
                  'plot_initial_configuration',plot_initial_configuration,...
                  'plot_each_load_step',plot_each_load_step,...
                  'plot_final_configuration',plot_final_configuration,...
                  'save_solution_vectors',save_solution_vectors);

if strcmp(physics,'thermo_elastic')
    sys_vars.heat_src = heat_src;
end
              
main_fes_model_1(sys_vars);